### ISSUE TITLE
Cannot set "Ajax" function

### ISSUE THREAD

**Issue by YuriChupyrkin** [canjs/can-model#62]
I use `can-model` **v3.0.3** and I cannot set `ajax` property.
We migrate the APP from canJs 2 to canJs 3 and `can-ajax` brakes the APP (the APP uses `$.ajax` and custom `jQuery` extensions for ajax).

It would be nice, if canJS team will fix it.
For example, `can-connect` lib has public `ajax` field.

Thanks

**Comment by YuriChupyrkin** [comment]
@justinbmeyer , could you fix it?

**Comment by justinbmeyer** [comment]
https://bitovi-community.slack.com/archives/CFC22NZ8A/p1553180391145600?thread_ts=1553155205.131900&cid=CFC22NZ8A

**Comment by cherifGsoul** [comment]
This is fixed in `V3.1.0` and `V4.1.0`
